### ISSUE TITLE
Dive?

### ISSUE THREAD

**Issue by violeterisb** [Morning-Person-Games/openworld-topwg#18]
Should we have a Dive? We have to have diving, right? 

Think that when they're near water a prompt will come up asking "Dive? (press button)" and do a little movement thing to act as if theyre diving.

**Comment by Reksford** [comment]
How about an Epic Dive collectable placed next to some choice cliff/water locations? I feel like there is no great 2D-minimap-style dive animation to be made you see; but I wouldn't mind being proven wrong on that front.

**Comment by violeterisb** [comment]
Yeah that's the real problem isn't it. It's gotta look great. So far my brainstorming has only come up with the idea of somehow showing a 3d dive. More brainstorming to come.

**Comment by Reksford** [comment]
Okay picture this: Opening of the game, 3D environment, you walk out of a cave, you're on top of a huge mountain on a little ledge. You walk to the edge, button prompt: DIVE. as you epic-ly fall toward your apparent doom the mini map in the corner grows to cover the entire screen, satisfying splash sound, now in control of the avatar arrow you walk away revealing a small speck of blue at the bottom of the minmap art cliff. Your journey begins.
