### ISSUE TITLE
Important assests.

### ISSUE THREAD

**Issue by Reksford** [Morning-Person-Games/openworld-topwg#2]
How do we want the pickups and player to look? Colored blocks?

**Comment by violeterisb** [comment]
I feel like there are two directions here... 
1. Assets are done by an artist and the map is actually really pretty and intriguing icons or...
2. Very simplistic block icons and map design.

**Comment by violeterisb** [comment]
Needed Assets (list updated as needed):

1) Map.
2) Assets for each type of pickup. 
3) Arrows for pickup inputs
4) Menu design/buttons
5) Skill Tree design/buttons
6) Main Menu design/buttons
7) Player Arrow/icon
