### ISSUE TITLE
Fishing mini game

### ISSUE THREAD

**Issue by violeterisb** [Morning-Person-Games/openworld-topwg#29]
Change the fishing pickup to a meter mini game

**Comment by violeterisb** [comment]
The way the fish moves is possibly too linear. If so there's most likely a way to move it based on a wave and not linearly that will need looking into. Also the player feedback for running out of time/failing might need some reworking as well but its at least easy to do so.
Public variables set for fishing on Pickups GO are as follows:
Player Fishing Speed - Controls the players movement speed
Fishing Time - the time the player has to be succeeding (multiplied by challenge level from skill tree)
Fish Multiplier - the speed multiplier for the fish movement

**Comment by zachberglund** [comment]
Updated the fish movement. This is looking bueno.

**Comment by violeterisb** [comment]
Updated the fish movement. This is looking bueno.
