### ISSUE TITLE
Create Skill Tree

### ISSUE THREAD

**Issue by violeterisb** [Morning-Person-Games/openworld-topwg#7]
Skill tree will have three paths of useless abilities besides the final ability at the end of each.

**Comment by violeterisb** [comment]
I'm thinking the fluff of the three paths are Casual, Speed-Runner, Completion. Casual tree lowers the prompt numbers on pickups, Speed-Runner tree unlocks a roll (that only makes you feel like you move faster) and a swim and Completion unlocks fast travel and guidance to nearest pickup of a chosen type.

**Comment by Reksford** [comment]
Offense tree, because passive incremental stat bonuses are the best 'skills' to unlock... right?
